# Telegram app id and hash
TELEGRAM_CLIENT_HASH = ''
TELEGRAM_CLIENT_ID = 0

# Telegram bot token from @BotFather
TELEGRAM_BOT_TOKEN = ''


# The username of the telegram bot.
TELEGRAM_BOT_USERNAME = ''

# Special client ID to access the sydney chat.
# It's not shared with the public to prevent abuse. If you got your hands on it, it's your responsability how you use it.
SYDNEY_CLIENT_ID = 0

# Postgres database connection string
POSTGRES_CONNECTION_STRING = ''

# DO NOT TOUCH!! AUTOMATICALLY GENERATED BY THE SCRIPT ON THE FIRST RUN
# b'IwjIw_ewCyTzBjdH6OQejKsr_e-hqc8PfsYN7CsAXRI='
COOKIE_ENCRYPTION_KEY = None
